import type { Metadata } from "next";
import "./globals.css";
import { ThemeButton } from "@/components/theme-button";
import Link from "next/link";
import { CounterProvider } from "@/contexts/counter-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="grid p-4">
          <ThemeButton />
          <nav>
            <ul>
              <li>
                <Link href={"/"}>Home</Link>
              </li>
              <li>
                <Link href={"/articles/create"}>Create Article</Link>
              </li>
            </ul>
          </nav>
        </header>
        <CounterProvider>{children}</CounterProvider>
      </body>
    </html>
  );
}
